import type { IntroScript } from './types'

export const introScript: IntroScript = {
  durationMs: 90000,
  markers: [
    { name: 'Cold Open', at: 0 },
    { name: 'Wake', at: 24000 },
    { name: 'Fracture', at: 48000 },
    { name: 'Hunt', at: 72000 },
    { name: 'Last Fade', at: 86000 },
  ],
  beats: [
    {
      id: 'blackout',
      at: 0,
      headline: 'No signal. Only breath.',
      sub: 'Hour 84 of the blackout',
      typewriter: { cps: 18, flicker: 0.35, scanline: true },
      transitionIn: 'soft',
      holdMs: 2200,
      transitionOut: 'soft',
    },
    {
      id: 'unravel',
      at: 4500,
      headline: 'Cities do not fall. They unravel.',
      sub: 'Quiet failures, stacked',
      typewriter: { cps: 19, flicker: 0.25, scanline: false },
      transitionIn: 'soft',
      holdMs: 2300,
    },
    {
      id: 'fog',
      at: 9000,
      headline: 'We learned to listen to the fog.',
      sub: 'It carries warnings',
      typewriter: { cps: 17, flicker: 0.4, scanline: true },
      glitch: { atOffsets: [600, 1400], strength: 0.6, ms: 140 },
      transitionOut: 'soft',
    },
    {
      id: 'leak',
      at: 13500,
      headline: 'Every light leak is a warning.',
      sub: 'Exposure tells on us',
      typewriter: { cps: 20, flicker: 0.2, scanline: false },
      transitionIn: 'soft',
      holdMs: 2000,
    },
    {
      id: 'tempo',
      at: 18000,
      headline: 'Hold fast. Move faster.',
      sub: 'Momentum is mercy',
      typewriter: { cps: 22, flicker: 0.3, scanline: true },
      glitch: { atOffsets: [500], strength: 0.8, ms: 160 },
      transitionIn: 'hard',
      transitionOut: 'soft',
    },
    {
      id: 'signal',
      at: 23000,
      headline: 'Static hides the real message.',
      sub: 'Pattern inside the noise',
      typewriter: { cps: 20, flicker: 0.3, scanline: true },
      glitch: { atOffsets: [600], strength: 0.7, ms: 140 },
      transitionIn: 'soft',
      holdMs: 2000,
    },
    {
      id: 'barricade',
      at: 28000,
      headline: 'Barricades are promises in wood.',
      sub: 'They splinter anyway',
      typewriter: { cps: 18, flicker: 0.25, scanline: false },
      transitionIn: 'soft',
      holdMs: 2200,
    },
    {
      id: 'trace',
      at: 33000,
      headline: 'We trace footsteps in ash.',
      sub: 'Someone was here',
      typewriter: { cps: 19, flicker: 0.3, scanline: true },
      transitionOut: 'soft',
    },
    {
      id: 'gaps',
      at: 38000,
      headline: 'The gaps between towers grow.',
      sub: 'We cross them anyway',
      typewriter: { cps: 18, flicker: 0.25, scanline: false },
      transitionIn: 'soft',
      holdMs: 2200,
    },
    {
      id: 'warning',
      at: 43000,
      headline: 'Do not look up too long.',
      sub: 'The skyline watches back',
      typewriter: { cps: 18, flicker: 0.35, scanline: true },
      glitch: { atOffsets: [700], strength: 0.65, ms: 140 },
      transitionIn: 'hard',
      transitionOut: 'soft',
    },
    {
      id: 'collapse',
      at: 48000,
      headline: 'Collapse is patient.',
      sub: 'It waits for balance',
      typewriter: { cps: 18, flicker: 0.3, scanline: false },
      transitionIn: 'soft',
      holdMs: 2300,
    },
    {
      id: 'shelter',
      at: 53000,
      headline: 'Shelter is a borrowed hour.',
      sub: 'Spend it wisely',
      typewriter: { cps: 20, flicker: 0.25, scanline: true },
      transitionIn: 'soft',
    },
    {
      id: 'maps',
      at: 58000,
      headline: 'Our maps are built from scars.',
      sub: 'Every route a compromise',
      typewriter: { cps: 18, flicker: 0.28, scanline: true },
      transitionOut: 'soft',
    },
    {
      id: 'breach',
      at: 63000,
      headline: 'The breach widens.',
      sub: 'We adapt or vanish',
      typewriter: { cps: 19, flicker: 0.25, scanline: false },
      glitch: { atOffsets: [600, 1600], strength: 0.7, ms: 120 },
      transitionIn: 'hard',
    },
    {
      id: 'ghosts',
      at: 68000,
      headline: 'Ghosts ride the wind.',
      sub: 'They leave no prints',
      typewriter: { cps: 17, flicker: 0.3, scanline: true },
      transitionIn: 'soft',
      holdMs: 2100,
    },
    {
      id: 'ignite',
      at: 73000,
      headline: 'We ignite the dark to see it.',
      sub: 'Brief flames, long shadows',
      typewriter: { cps: 20, flicker: 0.3, scanline: false },
      glitch: { atOffsets: [500], strength: 0.8, ms: 160 },
      transitionIn: 'hard',
    },
    {
      id: 'resolve',
      at: 78000,
      headline: 'Resolve is a quiet weapon.',
      sub: 'We carry it',
      typewriter: { cps: 18, flicker: 0.25, scanline: true },
      transitionIn: 'soft',
      transitionOut: 'soft',
    },
    {
      id: 'horizon',
      at: 84000,
      headline: 'Tomorrow is a contested word.',
      sub: 'Still, we speak it',
      typewriter: { cps: 16, flicker: 0.2, scanline: true },
      holdMs: 2600,
    },
  ],
}
