import type { IntroScript } from './types'

export const introScript: IntroScript = {
  durationMs: 58000,
  markers: [
    { name: 'Cold Open', at: 0 },
    { name: 'Signal Break', at: 18000 },
    { name: 'Collapse', at: 34000 },
    { name: 'Aftermath', at: 50000 },
  ],
  beats: [
    {
      id: 'blackout',
      at: 0,
      headline: 'No signal. Only breath.',
      sub: 'Hour 84 of the blackout',
      typewriter: { cps: 18, flicker: 0.35, scanline: true },
      transitionIn: 'soft',
      holdMs: 2200,
      transitionOut: 'soft',
    },
    {
      id: 'unravel',
      at: 4500,
      headline: 'Cities do not fall. They unravel.',
      sub: 'Quiet failures, stacked',
      typewriter: { cps: 19, flicker: 0.25, scanline: false },
      transitionIn: 'soft',
      holdMs: 2300,
    },
    {
      id: 'fog',
      at: 9000,
      headline: 'We learned to listen to the fog.',
      sub: 'It carries warnings',
      typewriter: { cps: 17, flicker: 0.4, scanline: true },
      glitch: { atOffsets: [600, 1400], strength: 0.6, ms: 140 },
      transitionOut: 'soft',
    },
    {
      id: 'leak',
      at: 13500,
      headline: 'Every light leak is a warning.',
      sub: 'Exposure tells on us',
      typewriter: { cps: 20, flicker: 0.2, scanline: false },
      transitionIn: 'soft',
      holdMs: 2000,
    },
    {
      id: 'tempo',
      at: 18500,
      headline: 'Hold fast. Move faster.',
      sub: 'Momentum is mercy',
      typewriter: { cps: 22, flicker: 0.3, scanline: true },
      glitch: { atOffsets: [500], strength: 0.8, ms: 160 },
      transitionIn: 'hard',
      transitionOut: 'soft',
    },
    {
      id: 'streets',
      at: 23500,
      headline: 'The streets remember our names.',
      sub: 'So we erase the sound',
      typewriter: { cps: 18, flicker: 0.25, scanline: false },
      holdMs: 2400,
    },
    {
      id: 'trust',
      at: 28500,
      headline: 'Trust breaks before doors do.',
      sub: 'We check every latch',
      typewriter: { cps: 19, flicker: 0.25, scanline: true },
      glitch: { atOffsets: [800, 1800], strength: 0.7, ms: 120 },
      transitionIn: 'soft',
    },
    {
      id: 'shadows',
      at: 33500,
      headline: 'When power fades, shadows decide.',
      sub: 'The map is a memory',
      typewriter: { cps: 18, flicker: 0.35, scanline: true },
      transitionIn: 'hard',
      transitionOut: 'soft',
    },
    {
      id: 'adapt',
      at: 38500,
      headline: 'We adapt, or disappear.',
      sub: 'No pause, no shelter',
      typewriter: { cps: 20, flicker: 0.2, scanline: false },
      holdMs: 2100,
    },
    {
      id: 'dawn',
      at: 43500,
      headline: 'Dawn is a rumor we chase.',
      sub: 'Still, we chase it',
      typewriter: { cps: 18, flicker: 0.3, scanline: true },
      glitch: { atOffsets: [700], strength: 0.6, ms: 140 },
      transitionIn: 'soft',
    },
    {
      id: 'quiet',
      at: 48500,
      headline: 'Stay quiet. Stay alive.',
      sub: 'Noise is a beacon',
      typewriter: { cps: 21, flicker: 0.35, scanline: false },
      transitionIn: 'hard',
      transitionOut: 'soft',
    },
    {
      id: 'end',
      at: 53500,
      headline: 'This is not the end.',
      sub: 'It is the next attempt',
      typewriter: { cps: 16, flicker: 0.2, scanline: true },
      holdMs: 2600,
    },
  ],
}
